# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot = {
    initrd = {
      availableKernelModules =
        [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      kernelModules = [ ];
    };
    kernelModules = [ "vboxdrv" "vboxnetadp" "vboxnet" ];
    kernelParams = [ "split_lock_detect=off" ];
    extraModulePackages = [ ];
  };
  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/7de0be9a-0b69-4b4c-9f3e-3249a210f290";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/CB29-A2D2";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };
    "/data" = {
      device = "/dev/disk/by-uuid/2c70eda9-6538-4851-81e6-0ef8a9426d95";
      fsType = "ext4";
    };
    "/arch" = {
      device = "/dev/disk/by-uuid/1f93f091-b052-4802-a533-1a1977b99fdb";
      fsType = "ext4";
    };
    "/wind" = {
      device = "/dev/disk/by-uuid/125C24165C23F361";
      fsType = "ntfs-3g";
    };
  };
  swapDevices = [{
    device = "/swapfile";
    size = 64 * 1024;
  }];
  zramSwap.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp24s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
