# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.kernelModules = [ "kvm-amd" "vboxdrv" "vboxpci" "vboxnetadp" "vboxnetflt" ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/713b4d92-14c6-4369-ba3d-84355a1018bd";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/AAAA-A7BA";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2ffeb6b4-e038-44c1-8e45-73df9a4286f3"; }
    ];

  nix.maxJobs = lib.mkDefault 16;
}
