#!/usr/bin/env zsh
if ! `sudo virsh list --all | grep "Debian" | grep running &> /dev/null`; then
	sudo virsh start "Debian 13"
else
	echo "Debian 13 is already running..."
fi
if ! `hyprctl clients -j | grep "Debian 13 on QEMU/KVM" &> /dev/null`; then 
	virt-manager --connect qemu:///system --show-domain-console "Debian 13"
else
	echo "The Debian 13 window is already open..."
fi
