#!/usr/bin/env zsh
# Get memory usage
info=$(nvidia-smi --query-gpu=memory.used,memory.total --format=csv,noheader,nounits)
used=$(echo $info | cut -d ',' -f 1)
total=$(echo $info | cut -d ',' -f 2)

# Calculate percentage
perc=$(R -e "round(100*$used/$total)" -q | head -n 2 | tail -n 1 | sed -E 's/^\[1\]\s//g')

# Determine class based on usage
if (( perc >= 90 )); then
    class="critical"
elif (( perc >= 75 )); then
    class="high"
elif (( perc >= 50 )); then
    class="medium"
elif (( perc >= 25 )); then
    class="low"
else
    class="idle"
fi

# Output JSON
printf '{"text":"%d%%","class":"%s"}' $perc "$class"