#!/usr/bin/env bash

current_layout_name=$(hyprctl devices -j | jq -r '
  .keyboards[]
  | select(.main == true)
  | .active_keymap
' | head -n1)

case "$current_layout_name" in
    *"Brazil"*) current_layout="br" ;;
    *"US"*) current_layout="us" ;;
    *) current_layout="us" ;;
esac

echo "{\"text\": \"$current_layout\", \"class\": \"$current_layout\"}"
