#!/usr/bin/env zsh
source $HOME/.zshrc
duration=$(echo "300" | rofi -dmenu -p "Duration (in seconds)" -filter "300")
logFile="$HOME/.cache/network-transfers.$(date +%s)"
logNetTransfers $duration "$logFile"
vim "$logFile"