#!/usr/bin/env zsh
if ! `ps ax | grep Outlive2025.exe | grep -v grep &> /dev/null`; then
	steam steam://rungameid/2948680
else

	# Find the workspace where Outlive is located
	ws=$(hyprctl clients -j | jq -r '.[] | select(.class=="steam_app_2948680") | .workspace.id' | tail -n 1)

	if [ -n "$ws" ]; then
    		# If found, switch to it
    		hyprctl dispatch workspace "$ws"
	fi 
fi
