#!/usr/bin/env bash
latestLog=$HOME/.cache/update
if [[ -f "$latestLog" ]]; then
    # Get 2nd line
    logLine=$(sed -n '2p' "$latestLog")
    if [[ -z "$logLine" ]]; then logLine="No Data"; fi
    
    # Write to override
    echo "$logLine" > /tmp/waybar_updates_msg
    
    # Signal Waybar to refresh custom/updates (signal 8)
    pkill -SIGRTMIN+8 waybar
else
    # Fallback
    echo "No Log" > /tmp/waybar_updates_msg
    pkill -SIGRTMIN+8 waybar
fi
