#!/usr/bin/env bash
user_input=$(rofi -dmenu -p "Enter wallpaper number")
notify-send "Changing wallpaper to number $user_input..."
$HOME/GitHub/mine/config/NixOS-configs/shell/hyprland/wallpaper $user_input
